name: Daily Security Pipeline

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

# Permissions globales pour checkout et upload SARIF
permissions:
  contents: read
  security-events: write

jobs:
  DependenciesAnalysis:
    name: Détection de patterns (Semgrep)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      security-events: write
    container:
      image: returntocorp/semgrep:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Semgrep CI
        run: semgrep ci --config p/java --sarif > semgrep-results.sarif
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      - name: Upload Semgrep SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results.sarif

  SourceCodeAnalysis:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: Analyse des dépendances (OSV)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run OSV Scanner
        uses: google/osv-scanner-action/osv-scanner-action@v1

      - name: Upload OSV SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: osv-results.sarif
