name: Security Workflow

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Allows manual triggering of the workflow for testing

jobs:
  osv-scanner:
    name: OSV Scanner Check
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run OSV Scanner
        uses: google/osv-scanner-action/osv-scanner-action@v1
        with:
          scan-args: '--output sarif --format sarif --recursive .'
          output-format: sarif
          output-file: osv-results.sarif

      - name: Upload OSV Scanner results to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: osv-results.sarif
          category: osv-scanner

  semgrep-analysis:
    name: Semgrep Analysis
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    permissions:
      security-events: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semgrep Analysis
        run: |
          semgrep \
            --config "p/java" \
            --sarif --output semgrep-results.sarif \
            .
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
name: Daily Security Pipeline

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read        # checkout & upload SARIF
  security-events: write # nécessaire pour envoyer les rapports SARIF

jobs:
  DependenciesAnalysis:
    name: Détection de patterns (Semgrep)
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep:latest
    permissions:
      contents: read
      actions: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Semgrep
        run: semgrep --config p/java --sarif --output semgrep-results.sarif

      - name: Upload Semgrep SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results.sarif

  SourceCodeAnalysis:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: Analyse des dépendances (OSV)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run OSV Scanner
        uses: google/osv-scanner-action@v2.0.2

      - name: Upload OSV SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

      - name: Upload Semgrep results to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep-results.sarif
          category: semgrep